<!DOCTYPE html>
<html lang="en">
	<head>
		<?php
			include("include/head-links.php");
		?>
		<title>Sai Laxmi Travels Bilaspur</title>
	</head>
	<body>
		<main>
			<?php
				include("include/header.php");
			?>
			<?php
				include("include/navbar.php");
			?>
			<?php
				include("include/slider.php");
			?>
			<?php
				include("include/book-a-car.php");
			?>
			<?php
				include("include/book-a-car-modal.php");
			?>
			<?php
				include("include/section-1.php");
			?>
			<?php
				include("include/inner-about.php");
			?>
			<?php
				include("include/inner-cars.php");
			?>
			<?php
				include("include/our-rental-plan.php");
			?>
			<?php
				include("include/inner-location.php");
			?>
			<?php
				include("include/trip-gallery.php");
			?>
			<?php
				include("include/footer.php");
			?>
			
		</main>
		<?php
			include("include/script.php");
		?>
	</body>
</html>